### ISSUE TITLE
unnecessary package.json

### ISSUE THREAD

**Issue by AndrewVanardennen** [VandeurenGlenn/backed-cli#8]
When only needing bower.json for dev web component. Backed still requires package.json.

**Comment by VandeurenGlenn** [comment]
@AndrewVanardennen Good catch!

In progress 43facfdd59b7366d1bc59626e6c026c489e0c850

**Comment by VandeurenGlenn** [comment]
Fixed 🎉 6fb6a96c2dca02b4b57e375c85ba4cf6bd8d6f97
